CREATE TABLE `PROJECT_STORAGE_USAGE` (
  `PROJECT_ID` BIGINT NOT NULL,
  `STORAGE_LOCATION_ID` BIGINT NOT NULL,
  `UPDATED_ON` TIMESTAMP NOT NULL,
  `SIZE_BYTES` BIGINT NOT NULL,
  PRIMARY KEY (`PROJECT_ID`, `STORAGE_LOCATION_ID`)
);