CREATE TABLE IF NOT EXISTS `ANNOTATIONS` (
  `ID` BIGINT NOT NULL,
  `ETAG` char(36) NOT NULL,
  `CREATED_ON` TIMESTAMP(3) NOT NULL,
  `MODIFIED_ON` TIMESTAMP(3) NOT NULL,
  `OBJECT_TYPE` enum('ENTITY','ENTITY_CONTAINER','PRINCIPAL','ACTIVITY','EVALUATION','SUBMISSION','EVALUATION_SUBMISSIONS','FILE','MESSAGE','WIKI','FAVORITE','ACCESS_REQUIREMENT','ACCESS_APPROVAL','TEAM','TABLE','ACCESS_CONTROL_LIST','PROJECT_SETTING','VERIFICATION_SUBMISSION','CERTIFIED_USER_PASSING_RECORD','FORUM','THREAD','REPLY','ENTITY_VIEW','USER_PROFILE','DATA_ACCESS_REQUEST','DATA_ACCESS_SUBMISSION','DATA_ACCESS_SUBMISSION_STATUS') NOT NULL,
  `OBJECT_ID` BIGINT NULL,
  `OBJECT_VERSION` BIGINT NOT NULL,
  `OBJECT_ANNOTATIONS` JSON NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_OBJECT_TYPE_ID_VERSION` (`OBJECT_ID`,`OBJECT_VERSION`,`OBJECT_TYPE`)
)